# Generated by Django 4.1 on 2022-11-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studioservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='props',
            options={'verbose_name': 'Реквизит', 'verbose_name_plural': 'Реквизиты'},
        ),
        migrations.AlterModelOptions(
            name='propscategory',
            options={'verbose_name': 'Категория реквизитов', 'verbose_name_plural': 'Категории реквизитов'},
        ),
    ]
