# Generated by Django 4.1 on 2022-11-01 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studioservices', '0002_alter_props_options_alter_propscategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='props', to='studioservices.propscategory'),
        ),
    ]
