# Generated by Django 4.1 on 2023-01-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studioservices', '0005_service_alter_propscategory_options_serviceimages_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceImages',
            new_name='ServiceImage',
        ),
    ]
