# Generated by Django 4.1 on 2023-02-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studioservices', '0007_servicecategory_alter_propscategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='url_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название реквизита латиница'),
        ),
        migrations.AddField(
            model_name='propscategory',
            name='url_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории латиница'),
        ),
        migrations.AddField(
            model_name='service',
            name='url_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги латиница'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='url_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории латиница'),
        ),
    ]
