# Generated by Django 4.1 on 2023-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название латиница'),
            preserve_default=False,
        ),
    ]
