# Generated by Django 4.1 on 2023-01-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
