# Generated by Django 4.1 on 2023-02-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подборки')),
                ('url_name', models.CharField(max_length=255, verbose_name='Название подборки латиница')),
            ],
            options={
                'verbose_name': 'Подбока',
                'verbose_name_plural': 'Подборки',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('url_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название фильма латиница')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('pg_rating', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возрастное ограничение')),
                ('description', models.TextField(help_text='Максимально 400 символов', max_length=400, verbose_name='Описание фильма')),
                ('type', models.CharField(max_length=255, verbose_name='Тип фильма')),
                ('kind', models.CharField(max_length=255, verbose_name='Вид фильма')),
                ('footage', models.CharField(max_length=255, verbose_name='Метраж')),
                ('audio', models.CharField(max_length=255, verbose_name='Звук')),
                ('restoration_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год восстановления')),
                ('poster', models.ImageField(null=True, upload_to='movie', verbose_name='Постер фильма')),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер в Youtube')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('url_name', models.CharField(max_length=255, verbose_name='ФИО латиница')),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина')], default=1, verbose_name='Пол')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('appearance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешность')),
                ('profession', models.CharField(max_length=255, verbose_name='Профессия')),
                ('assistant', models.IntegerField(choices=[(1, 'Не является ассистентом'), (2, 'ассистент директорв'), (3, 'ассистент сценариста'), (4, 'ассистент оператора'), (5, 'ассистент художника-гримера'), (6, 'ассистент художника-декоратора'), (7, 'ассистент художника-реквизитора')], default=1, verbose_name='Ассистент')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('photo', models.ImageField(null=True, upload_to='person', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Деятель искусства',
                'verbose_name_plural': 'Деятели искусства',
            },
        ),
        migrations.CreateModel(
            name='PersonInMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.IntegerField(choices=[(1, 'Режиссёр'), (2, 'Сценарист'), (3, 'Композитор'), (4, 'Художник - постановщик'), (5, 'Актёр')], default=5)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='art.movie')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='art.person')),
            ],
            options={
                'verbose_name': 'Участник фильма',
                'verbose_name_plural': 'Участники фильма',
            },
        ),
        migrations.CreateModel(
            name='MovieInCompilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compilation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_in_compilation', to='art.compilation')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_in_compilation', to='art.movie')),
            ],
            options={
                'verbose_name': 'Фильм в подбоке',
                'verbose_name_plural': 'Фильмы в подбоках',
            },
        ),
    ]
