# Generated by Django 4.1 on 2022-08-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('pg_rating', models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('type', models.CharField(max_length=255, verbose_name='Тип фильма')),
                ('kind', models.CharField(max_length=255, verbose_name='Вид фильма')),
                ('footage', models.CharField(max_length=255, verbose_name='Метраж')),
                ('audio', models.CharField(max_length=255, verbose_name='Звук')),
                ('restoration_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год восстановления')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('profession', models.CharField(max_length=255, verbose_name='Род деятельности')),
                ('bio', models.TextField(verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Деятель искусства',
                'verbose_name_plural': 'Деятели искусства',
            },
        ),
        migrations.CreateModel(
            name='PersonInMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.IntegerField(choices=[(1, 'Режиссёр'), (2, 'Сценарист'), (3, 'Композитор'), (4, 'Художник - постановщик'), (5, 'Актёр')], default=5)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.movie')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='art.person')),
            ],
            options={
                'verbose_name': 'Участник фильма',
                'verbose_name_plural': 'Участники фильма',
            },
        ),
    ]
