# Generated by Django 4.1 on 2023-02-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Возраст'),
            preserve_default=False,
        ),
    ]
