# Generated by Django 4.1 on 2022-08-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie', verbose_name='Постер фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер в Youtube'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to='person', verbose_name='Фото'),
        ),
    ]
