# Generated by Django 4.1 on 2023-01-31 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_compilation_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilation',
            name='url_name',
        ),
    ]
