# Generated by Django 4.1 on 2023-02-12 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='art.profession'),
        ),
    ]
