# Generated by Django 4.1 on 2023-02-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_alter_person_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Профессия')),
                ('url_name', models.CharField(max_length=255, unique=True, verbose_name='Профессия латиница')),
            ],
            options={
                'verbose_name': 'Группа Профессии',
                'verbose_name_plural': 'Группы Профессий',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='assistant',
            field=models.IntegerField(choices=[(1, 'Не является ассистентом'), (2, 'ассистент художника-гримера'), (3, 'ассистент художника-декоратора'), (4, 'ассистент художника-реквизитора')], default=1, verbose_name='Ассистент'),
        ),
        migrations.AddField(
            model_name='profession',
            name='profession_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professions', to='art.professiongroup'),
        ),
    ]
