# Generated by Django 4.1 on 2023-01-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_remove_compilation_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilation',
            name='url_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название подборки латиница'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='url_name',
            field=models.CharField(default=2, max_length=255, verbose_name='ФИО латиница'),
            preserve_default=False,
        ),
    ]
