# Generated by Django 4.1 on 2023-02-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_person_assistant_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=5, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='assistant',
            field=models.IntegerField(choices=[(1, 'Не является ассистентом'), (2, 'ассистент директорв'), (3, 'ассистент сценариста'), (4, 'ассистент оператора'), (5, 'ассистент художника-гримера'), (6, 'ассистент художника-декоратора'), (7, 'ассистент художника-реквизитора')], default=1, verbose_name='Ассистент'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.PositiveIntegerField(choices=[(1, 'Мужчина'), (2, 'Женщина')], default=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(max_length=255, verbose_name='Профессия'),
        ),
    ]
