# Generated by Django 4.1 on 2023-02-12 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_professiongroup_alter_person_assistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinmovie',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_in_movie', to='art.profession'),
        ),
    ]
