# Generated by Django 4.1 on 2023-02-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_movie_rating_alter_person_assistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=1, verbose_name='Рейтинг'),
        ),
    ]
