# Generated by Django 4.1 on 2022-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_alter_personinmovie_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(help_text='Максимально 400 символов', max_length=400, verbose_name='Описание фильма'),
        ),
    ]
