# Generated by Django 4.1 on 2022-11-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_alter_movie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подборки')),
            ],
        ),
        migrations.CreateModel(
            name='MovieInCompilation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compilation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_in_compilation', to='art.compilation')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_in_compilation', to='art.movie')),
            ],
        ),
    ]
