# Generated by Django 4.1 on 2022-11-01 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_compilation_movieincompilation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilation',
            options={'verbose_name': 'Подбока', 'verbose_name_plural': 'Подборки'},
        ),
        migrations.AlterModelOptions(
            name='movieincompilation',
            options={'verbose_name': 'Фильм в подбоке', 'verbose_name_plural': 'Фильмы в подбоках'},
        ),
    ]
