# Generated by Django 4.1 on 2023-02-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='appearance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешность'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pg_rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
    ]
