# Generated by Django 4.1 on 2023-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_alter_compilation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url_name',
            field=models.CharField(default='q', max_length=255, unique=True, verbose_name='Название фильма латиница'),
        ),
    ]
