# Generated by Django 4.1 on 2023-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_movie_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название фильма латиница'),
        ),
    ]
